on:
  push:
  schedule:
    - cron: '0 0 * * 6'
    
jobs:
  publish:
    runs-on: ubuntu-latest
      
    name: Build Chrome OS releases database
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 65536
          swap-size-mb: 64
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'

      - name: download repo
        uses: actions/checkout@v4
      
      - name: cache downloads
        uses: actions/cache@v4
        with:
          path: downloads
          key: downloads-${{ github.ref }}-${{ github.run_id }}
          restore-keys: |
            downloads-${{ github.ref }}
      
      - name: install deps
        run: |
          set -x
          sudo apt-get install -y vboot-kernel-utils binwalk pcregrep
          python3 -m venv .venv
          source .venv/bin/activate
          pip3 install -r requirements.txt
      
      - name: run build
        run: |
          set -x
          source .venv/bin/activate
          python3 main.py

      - name: upload database as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: data
          path: data/data.json
          compression-level: 9
      
      - name: upload downloads as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: downloads
          path: downloads/
          compression-level: 9

      - name: publish database
        run: |
          set -x
          git config --global user.name "GitHub Actions"
          git config --global user.email "<>"
          cd data
          git clone "https://${{ secrets.GH_TOKEN }}@github.com/MercuryWorkshop/chromeos-releases-data" -b main
          cd chromeos-releases-data
          cp ../data.json ./
          if [ ! "$(git status -s)" ]; then
            exit 0
          fi
          git add .
          git commit -m "update data.json"
          git push origin main

  workflow-keepalive:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: liskin/gh-workflow-keepalive@v1
